apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fcg
type: Opaque
data:
  ConnectionStrings__DefaultConnection: SG9zZdd1wb3N0Z3Jlcy1cy1jYXRhbG9nCi4uLg==
  JwtSettings__SecretKey: RkNHX1NFQ1JFVF9LRV1fQ0hBTkdFX01OX1BST0RfMzJDSEFSuyE=
  RabbitMQ__Username: ZmNn
  RabbitMQ__Password: ZmNnQHBhc3M=